export const fetchHomepage = async () => {
  return [
    { id: 1, Gen: 9, Specialize: "Software Engineer", Group: 1 },
    { id: 2, Gen: 9, Specialize: "Software Engineer", Group: 2 },
    { id: 3, Gen: 9, Specialize: "Software Engineer", Group: 3 },
    { id: 4, Gen: 9, Specialize: "Software Engineer", Group: 4 },
    { id: 5, Gen: 9, Specialize: "Software Engineer", Group: 5 },
    { id: 6, Gen: 9, Specialize: "Data Scientist", Group: 1 },
    { id: 7, Gen: 9, Specialize: "Data Scientist", Group: 2 },
    { id: 8, Gen: 9, Specialize: "Data Scientist", Group: 3 },
    { id: 9, Gen: 9, Specialize: "Data Scientist", Group: 4 },
    { id: 10, Gen: 9, Specialize: "Data Scientist", Group: 5 },

    { id: 11, Gen: 10, Specialize: "Software Engineer", Group: 1 },
    { id: 12, Gen: 10, Specialize: "Software Engineer", Group: 2 },
    { id: 13, Gen: 10, Specialize: "Software Engineer", Group: 3 },
    { id: 14, Gen: 10, Specialize: "Software Engineer", Group: 4 },
    { id: 15, Gen: 10, Specialize: "Software Engineer", Group: 5 },
    { id: 16, Gen: 10, Specialize: "Data Scientist", Group: 1 },
    { id: 17, Gen: 10, Specialize: "Data Scientist", Group: 2 },
    { id: 18, Gen: 10, Specialize: "Data Scientist", Group: 3 },
    { id: 19, Gen: 10, Specialize: "Data Scientist", Group: 4 },
    { id: 20, Gen: 10, Specialize: "Data Scientist", Group: 5 },

    { id: 21, Gen: 11, Specialize: "Software Engineer", Group: 1 },
    { id: 22, Gen: 11, Specialize: "Software Engineer", Group: 2 },
    { id: 23, Gen: 11, Specialize: "Software Engineer", Group: 3 },
    { id: 24, Gen: 11, Specialize: "Software Engineer", Group: 4 },
    { id: 25, Gen: 11, Specialize: "Software Engineer", Group: 5 },
    { id: 26, Gen: 11, Specialize: "Data Scientist", Group: 1 },
    { id: 27, Gen: 11, Specialize: "Data Scientist", Group: 2 },
    { id: 28, Gen: 11, Specialize: "Data Scientist", Group: 3 },
    { id: 29, Gen: 11, Specialize: "Data Scientist", Group: 4 },
    { id: 30, Gen: 11, Specialize: "Data Scientist", Group: 5 },
  ];
};